### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by pinggod** [pinggod/hexo-theme-jekyll#1]
## HOME

![hexo-theme-jekyll-home](https://cloud.githubusercontent.com/assets/9530963/10627194/0ceeb9bc-77e9-11e5-918b-c978d444bbd3.png)

## POST-LIST

![hexo-theme-jekyll-blog](https://cloud.githubusercontent.com/assets/9530963/10627180/ed95a832-77e8-11e5-90d8-c0ecb8224636.png)

## POST

![hexo-theme-jekyll-post](https://cloud.githubusercontent.com/assets/9530963/10627185/f6759886-77e8-11e5-972a-53c395c6036a.png)

**Comment by nhsprite** [comment]
Can I change the lion image to my custom image?

**Comment by pinggod** [comment]
@nhsprite You can do whatever you can.

p.s. If anyone have good idea about the logo of this theme, please comment here 😄。

**Comment by nhsprite** [comment]
hmm...the logo is nice, but I want to change to my own logo =。=....Anyway, how can I add comment to this theme?

**Comment by pinggod** [comment]
@nhsprite 

Just attach logo image file by dragging & dropping or pasting to the comment section.
