### ISSUE TITLE
在archive.jade添加`include _sidebar/toc`之后报错

### ISSUE THREAD

**Issue by lawlietfans** [pinggod/hexo-theme-jekyll#3]
`layout/_sidebar/`包含post.jade、tag.jade、和toc.jade三个部件，理论上都可以添加到archive.jade

    extends _partial/layout

    block content
        include _mixin/post
        +archivePost()
        aside.sidebar
            include _sidebar/tag
            include _sidebar/post

但是添加`include _sidebar/toc`之后回报错如下：

    Unhandled rejection TypeError: e:\workspace\github\blog-github\themes\jekyll\lay
    out\_sidebar\toc.jade:1
      > 1| if toc(page.content, {list_number: false})
        2|   h3 文章目录
        3|   != list_tags({amount: 5, show_count: false})
        4|

**Comment by pinggod** [comment]
`toc.jade` 调用了Hexo内建的辅助函数 [toc()](https://hexo.io/zh-cn/docs/helpers.html#toc)，该函数需要接收字符串形式的文章内容（`page.content`），所以在 `archive.jade` 中引用 `toc.jade` 会因为找不到 `page.content` 而报错。

`archive.jade` 是一个归档页面，该页面列述多篇文章，所以无法适用该组件。此外，目前还没有编写该组件的样式，所以 `toc` 只是存在但没有被任何页面所引用。

**Comment by lawlietfans** [comment]
之前把它理解成右侧的博文列表了。。。那在单独一篇文章中也无法启用目录吗？

**Comment by pinggod** [comment]
@lawlietfans 

单独的文章页面对应 `post.jade` 这个模板，去掉 `toc` 前面的注释即可。此外，使用前需要用设置 `toc` 部分的样式。

**Comment by lawlietfans** [comment]
嗯，谢谢啦
