### ISSUE TITLE
可能是中文的问题导致页面超宽

### ISSUE THREAD

**Issue by twang2218** [pinggod/hexo-theme-jekyll#4]
您好，不好意思，我知道这个项目已经停止了，不过我很喜欢这个主题，所以在尝试使用它。碰到了一些问题。不知道是不是因为中文换行的问题，还是代码过长的原因，我的文章使用这个主题后，变得超宽。

![2016-07-14 15 17 04](https://cloud.githubusercontent.com/assets/6299096/16828813/8e4525d6-49d6-11e6-87ef-2c11ba25f125.png)
![2016-07-14 15 17 17](https://cloud.githubusercontent.com/assets/6299096/16828820/99bae23e-49d6-11e6-86ca-0f020f038838.png)

请问，这种情况我应该修改哪里？谢谢。

**Comment by pinggod** [comment]
@twang2218 可以把这篇博文的 markdown 文件发给我邮箱 pinggodstudio@gmail.com 晚些时候我试一下

**Comment by twang2218** [comment]
@pinggod 已经发了，麻烦您了，谢谢。

**Comment by pinggod** [comment]
@twang2218 是因为没有限制容器宽度、没有为长文本设置 word-wrap 样式的问题，已经提交了更新，更新主题即可。

**Comment by twang2218** [comment]
`pull`了新的版本，可以了，非常感谢。
